//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtocolSim
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Login
    {
        
        public int Id { get; set; }
        [DisplayName("שם משתמש")]
        public string UserName { get; set; }
        [DisplayName("סיסמא")]
        public string Password { get; set; }
        [DisplayName("חוק משתמש")]
        public string RoleName { get; set; }

    }
}
