//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtocolSim
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class OnlyUser
    {
        public int Sid { get; set; }
        [DisplayName("שם יחידה/ לקוח")]
        public string Unitname { get; set; }
        [DisplayName("יצירת קשר")]
        public string Contact { get; set; }
    }
}
