//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtocolSim
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Sim
    {
        public int SId { get; set; }
        [Required]
        [DisplayName("שם ספק")]
        public string Company_Name { get; set; }
        [Required]
        [DisplayName("מספר פלאפון")]
        public string PunNumber { get; set; }
        [Required]
        [DisplayName("IMEI SIM")]
        public string ImeiSim { get; set; }
        [DisplayName("תוכנית")]
        public string Packageplan { get; set; }
        public string Apn { get; set; }
        public string Ip { get; set; }
        [DisplayName("תאריך התחלת שירות")]
        public Nullable<System.DateTime> StartDate { get; set; }
        [DisplayName("שם יחידה/ לקוח")]
        public string Unitname { get; set; }
        [DisplayName("יצירת קשר")]
        public string Contact { get; set; }
        [DisplayName("שם המכשיר")]
        public string DeviceName { get; set; }
        [Required]
        [DisplayName("IMEI מכשיר")]
        public string ImeiDevice { get; set; }
        [DisplayName("הערות")]
        public string Note { get; set; }
    }
}
